### ISSUE TITLE
Create Batch Relation

### ISSUE THREAD

**Issue by Rukshan1999** [Rukshan-Play-Ground/student-management-queries#10]
![img](https://github.com/user-attachments/assets/244d210a-7389-4427-9d48-790c614a43bd)

**Comment by shanuka1198** [comment]
@Rukshan1999 mokadda me kiyawaneee..mata therumak ne mokadda kiyawaneee kiyala oya

**Comment by shanuka1198** [comment]
@Rukshan1999 Please Review My Work
